# netlify.toml

[build]
  # Définir le répertoire contenant les fichiers statiques à déployer
  publish = "frontend"

  # Commande pour construire ton site (si nécessaire, comme pour React ou autre)
  # Dans ton cas, il n'y a pas de build nécessaire si tu utilises uniquement HTML/CSS/JS simples.
  # command = "npm run build" (Si tu utilises un framework comme React, Angular, etc.)
  
  # Si tu veux des fonctions backend sur Netlify (ex : pour utiliser Cloud Functions)
  functions = "backend"

[dev]
  # Répertoire de ton application frontend pour tests locaux
  command = "npm run start"  # Si tu veux utiliser une commande pour tester le site localement
  port = 3000
  publish = "frontend"

[[redirects]]
  # Rediriger tout le trafic vers l'index.html (pour des Single Page Applications)
  from = "/*"
  to = "/index.html"
  status = 200
